WARNING: Ignoring invalid distribution -erminado (/mnt/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -cipy (/mnt/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages)
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/100 [00:00<?, ?it/s]
  0%|          | 0/18 [00:00<?, ?it/s][A
  6%|▌         | 1/18 [00:00<00:01,  9.88it/s][A
 11%|█         | 2/18 [00:00<00:01,  8.74it/s][A
 17%|█▋        | 3/18 [00:00<00:01,  8.40it/s][A
 22%|██▏       | 4/18 [00:00<00:01,  8.13it/s][A
 28%|██▊       | 5/18 [00:00<00:01,  7.46it/s][A
 33%|███▎      | 6/18 [00:00<00:01,  7.54it/s][A
 39%|███▉      | 7/18 [00:00<00:01,  6.93it/s][A
 44%|████▍     | 8/18 [00:01<00:01,  7.02it/s][A
 56%|█████▌    | 10/18 [00:01<00:01,  7.45it/s][A
 61%|██████    | 11/18 [00:01<00:00,  7.53it/s][A
 67%|██████▋   | 12/18 [00:01<00:00,  7.89it/s][A
 72%|███████▏  | 13/18 [00:01<00:00,  7.86it/s][A
 78%|███████▊  | 14/18 [00:01<00:00,  7.75it/s][A
 83%|████████▎ | 15/18 [00:01<00:00,  7.46it/s][A
 89%|████████▉ | 16/18 [00:02<00:00,  7.95it/s][A
 94%|█████████▍| 17/18 [00:02<00:00,  7.90it/s][A
100%|██████████| 18/18 [00:02<00:00,  7.96it/s][A100%|██████████| 18/18 [00:02<00:00,  7.74it/s]

  0%|          | 0/10 [00:00<?, ?it/s][A
 10%|█         | 1/10 [00:01<00:15,  1.68s/it][A
 20%|██        | 2/10 [00:09<00:42,  5.29s/it][A
 30%|███       | 3/10 [00:29<01:22, 11.80s/it][A
 40%|████      | 4/10 [01:01<01:59, 19.96s/it][A
 50%|█████     | 5/10 [01:39<02:11, 26.36s/it][A
 60%|██████    | 6/10 [02:09<01:51, 27.83s/it][A
 70%|███████   | 7/10 [02:27<01:12, 24.32s/it][A
 80%|████████  | 8/10 [02:33<00:37, 18.60s/it][A
 90%|█████████ | 9/10 [02:34<00:13, 13.23s/it][A
100%|██████████| 10/10 [02:34<00:00,  9.19s/it][A100%|██████████| 10/10 [02:34<00:00, 15.49s/it]
  0%|          | 0/100 [02:37<?, ?it/s]
Traceback (most recent call last):
  File "test_tab_stability.py", line 497, in <module>
    presence_list[feat_pos] = 1
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
